model_list:
  - model_name: anytoolai.default_text
    litellm_params:
      model: openai/gpt-5.4-nano
      api_key: env/OPENAI_API_KEY
      reasoning_effort: medium

router_settings:
  routing_strategy: simple-shuffle
  enable_pre_call_checks: true
